//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public bool Published { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public string UserId { get; set; }
    }
}
